package com.app.todoapp.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

/**
 * Represents a single task in the to-do application
 * This class is a JPA entity, meaning it maps to a database table.
 */
@Entity
@Data  // Lombok annotation: generates getters, setters, toString, equals, and hashCode automatically
public class Task {
    /**
     * Primary key for the Task entity.
     * It will be auto-generated by the database (unique ID for each task).
     */
   @Id
   @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String title;

    /**
     * Status of the task.
     * false = not completed, true = completed
     */
    private boolean completed;



}
